### ISSUE TITLE
How to connect a MongoDB

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#315]
Please help, i have a modgo database from mongoDB.com How to connect my datase on eden?

**Comment by serumanooo** [comment]
1- enable uri mode
![image](https://github.com/diamond-rip/Eden/assets/132185379/acf3d146-3b70-41de-95c0-7bb2c570287c)
2- click here
![image](https://github.com/diamond-rip/Eden/assets/132185379/0f271cb1-f249-4327-924e-8cbf89bbeef1)
3- here
![image](https://github.com/diamond-rip/Eden/assets/132185379/145a06c3-dec4-4b9e-b19e-660fe2d08c66)
4- copy this and replace this with the password you created for the database
![image](https://github.com/diamond-rip/Eden/assets/132185379/7c663058-6622-4b78-98b1-51037e38bdae)
5- fill this area with the name of the database and the uri you just copied
![image](https://github.com/diamond-rip/Eden/assets/132185379/77ad1688-a13c-487b-b5ae-dec0bb6c6ff0)

**Comment by serumanooo** [comment]
thats what worked for me

**Comment by liexes** [comment]
Dont work for me bro
![Captura de pantalla 2023-05-22 180902](https://github.com/diamond-rip/Eden/assets/121281203/7aaf6436-f030-4bcb-9066-46089b21ca90)
Please help @GoodestEnglish

**Comment by serumanooo** [comment]
> Dont work for me bro @serumanooo ![Captura de pantalla 2023-05-22 180902](https://user-images.githubusercontent.com/121281203/239967244-7aaf6436-f030-4bcb-9066-46089b21ca90.png) Please help @GoodestEnglish

this happened to me one time, i restarted the server and it never happened again, sorry, i cant help you

**Comment by Antoniova1** [comment]
the same thing happens to me too
https://pastebin.com/iUPE2SjV

and this is another log after i rebooted the server
https://pastebin.com/7xDaXmTZ

**Comment by Antoniova1** [comment]
the same thing happens to me too
https://pastebin.com/iUPE2SjV

and this is another log after i rebooted the server
https://pastebin.com/7xDaXmTZ
![Eden](https://github.com/diamond-rip/Eden/assets/108409110/084c7faf-e17e-445b-8112-e4a1b6811003)

**Comment by serumanooo** [comment]
> 

for me it happened like this: 
i restarted the server and i went to sleep
at the next day my friends told me they could not join the server, i tried to join and got this error, i restarted and even forgot about it, and magically the server was working, so idk what i did to fix it
it never happened again

**Comment by liexes** [comment]
> for me it happened like this:
> i restarted the server and i went to sleep
> at the next day my friends told me they could not join the server, i tried to join and got this error, i restarted and even forgot about it, and magically the server was working, so idk what i did to fix it
> it never happened again

[16:19:22 WARN]: org.apache.commons.lang.UnhandledException: Plugin Eden v1.1.16-BETA-7916368 generated an exception while executing task 60
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$$Lambda$1868/1608756763@7221ed1a. Client view of cluster state is {type=REPLICA_SET, servers=[{address=ac-auo9762-shard-00-01.tateden.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=ac-auo9762-shard-00-02.tateden.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=ac-auo9762-shard-00-00.tateden.mongodb.net:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]
        at com.mongodb.internal.connection.BaseCluster.createTimeoutException(BaseCluster.java:428)
        at com.mongodb.internal.connection.BaseCluster.selectServer(BaseCluster.java:125)
        at com.mongodb.internal.connection.AbstractMultiServerCluster.selectServer(AbstractMultiServerCluster.java:54)
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:145)
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:100)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:285)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:177)
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130)
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
        at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:116)
        at com.mongodb.client.internal.MongoIterableImpl.into(MongoIterableImpl.java:125)
        at rip.diamond.practice.leaderboard.impl.KitLeaderboard.update(KitLeaderboard.java:32)
        at java.util.HashMap$Values.forEach(HashMap.java:982)
        at rip.diamond.practice.leaderboard.LeaderboardManager.update(LeaderboardManager.java:41)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
        ... 3 more

**Comment by liexes** [comment]
Is solved! the error is in network access, i add ip to access anyware, and work now! @Antoniova1

**Comment by Antoniova1** [comment]
> 

I have it like this and it still doesn't work
![Screenshot_20230524-153204_Chrome](https://github.com/diamond-rip/Eden/assets/108409110/ebb713a7-cbf4-4d32-a141-1b7afbc4103d)

**Comment by serumanooo** [comment]
> > 
> 
> I have it like this and it still doesn't work should i add something else? ![Screenshot_20230524-153204_Chrome](https://user-images.githubusercontent.com/108409110/240746853-ebb713a7-cbf4-4d32-a141-1b7afbc4103d.jpg)

if youre using a online host, try addind the ip of your server
![image](https://github.com/diamond-rip/Eden/assets/132185379/b8d7ff2c-f353-4065-9f73-47904ae0a521)
and make sure youre using URI mode, i cant connect without it, but if you want to try without it, feel free to do it

**Comment by Antoniova1** [comment]
> > > 
> > 
> > 
> > I have it like this and it still doesn't work should i add something else? ![Screenshot_20230524-153204_Chrome](https://user-images.githubusercontent.com/108409110/240746853-ebb713a7-cbf4-4d32-a141-1b7afbc4103d.jpg)
> 
> if youre using a online host, try addind the ip of your server ![image](https://user-images.githubusercontent.com/132185379/240751621-b8d7ff2c-f353-4065-9f73-47904ae0a521.png) and make sure youre using URI mode, i cant connect without it, but if you want to try without it, feel free to do it

thanks for the help, I have added the ip of my host but the same error occurs, I don't know more I can do to solve it, I have the uri-mode: true

**Comment by serumanooo** [comment]
> > > > 
> > > 
> > > 
> > > I have it like this and it still doesn't work should i add something else? ![Screenshot_20230524-153204_Chrome](https://user-images.githubusercontent.com/108409110/240746853-ebb713a7-cbf4-4d32-a141-1b7afbc4103d.jpg)
> > 
> > 
> > if youre using a online host, try addind the ip of your server ![image](https://user-images.githubusercontent.com/132185379/240751621-b8d7ff2c-f353-4065-9f73-47904ae0a521.png) and make sure youre using URI mode, i cant connect without it, but if you want to try without it, feel free to do it
> 
> thanks for the help, I have added the ip of my host but the same error occurs, I don't know more I can do to solve it, I have the uri-mode: true

i think the reason is what @GoodestEnglish said:
> This error is typically caused by a failed authentication attempt when attempting to connect to a MongoDB Atlas cluster. This could be due to incorrect credentials or a configuration issue with Atlas.

so try to recreate the mongodb database (you need to delete that one to create another free one)
at the creation of the database, note the user and password at like, notepad or something
im  saying this because i havent found any way to see this informations at mongodb, so i just created a new one when i forgot the password

and make what i said before:
![image](https://github.com/diamond-rip/Eden/assets/132185379/550ad419-05e6-40fe-a591-17f75e161f98)

if this fix your problem, maybe you just misstyped the password before or used the wrong one *(its not the password of your mongodb account)*

*dont forget to put the right database name in config.yml*

if this dont solve your problem, then idk how to help you, but i dont believe its a bug because it works fine for me and other people
so i hope somebody helps you to fix this or maybe you will figure out whats the problem

**Comment by Antoniova1** [comment]
> 

I've been for hours and it's a pity :(, I created new databases, I used the correct password and username and still the same problem, I have no idea what is happening, I only see errors in the console and at the moment If I want to join the server, I can't join, it stays on the screen downloading terrain, but if you deactivated mongo mode, I can join

**Comment by djtheta** [comment]
same

**Comment by serumanooo** [comment]
> > 
> 
> I've been for hours and it's a pity :(, I created new databases, I used the correct password and username and still the same problem, I have no idea what is happening, I only see errors in the console and at the moment If I want to join the server, I can't join, it stays on the screen downloading terrain, but if you deactivated mongo mode, I can join

yeah mongodb has a lot of problems, i personally dont like it, it caused me many issues

**Comment by Antoniova1** [comment]
> > > 
> > 
> > 
> > I've been for hours and it's a pity :(, I created new databases, I used the correct password and username and still the same problem, I have no idea what is happening, I only see errors in the console and at the moment If I want to join the server, I can't join, it stays on the screen downloading terrain, but if you deactivated mongo mode, I can join
> 
> yeah mongodb has a lot of problems, i personally dont like it, it caused me many issues

Do you know any other alternative?

**Comment by serumanooo** [comment]
> Do you know any other alternative?

eden does not support any database other than mongodb, i think mysql would be way better, but i dont understand about databases so i can't say anything about it
