### ISSUE TITLE
about the 'null' thing

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#382]
![image](https://github.com/diamond-rip/Eden/assets/132185379/37ad225a-4619-47e5-a5fd-9c77a7e1d17e)

![image](https://github.com/diamond-rip/Eden/assets/132185379/c03309f0-622e-4fac-aa78-4181b2e13fba)
its not working

**Comment by GoodestEnglish** [comment]
Try it again with the version i just published.

**Comment by serumanooo** [comment]
> Try it again with the version i just published.

sorry, i forgot about this issue, i guess its solved, ill confirm it tomorrow (im almost 99% right that is solved)
ill close this issue, but if its not solved, ill just open a new one
